### ISSUE TITLE
Pubmed scraping fails with exception

### ISSUE THREAD

**Issue by mmpfister** [collabovid/collabovid#34]
## Problem
At the moment, the Pubmed scraping process aborts by throwing a `requests.exceptions.ChunkedEncodingError`. This happens when scraping new Pubmed articles and when updating existing ones, since both rely on fetching all results of our search query. It is an internal error of the pymed package (which is unfortunately discontinued).

## Reason
It does **not** seem to happen due to a violation of the rate limit (which is [3 requests per second](https://www.ncbi.nlm.nih.gov/books/NBK25497/#_chapter2_Usage_Guidelines_and_Requiremen_) without an API key). The pymed package takes care of this.

Instead, the error seems to be caused by one (or more) "invalid" Pubmed IDs (that the initial internal query returns) and that is then queried using the [EFetch API](https://www.ncbi.nlm.nih.gov/books/NBK25499/#_chapter4_EFetch_). Because pymed queries the EFetch API with subsequent chunks of IDs, the error does only occur when these IDs are part of the current chunk.

[Attached](https://github.com/collabovid/collabovid/files/6407220/possibly_problematic_pubmed_ids.txt) is a chunk (list of Pubmed IDs) that causes such an error, when queried using the API.

## Solution
We should probably fork the pymed package, dig deeper to find "problematic" Pubmed IDs that cause the issue and fix the cause.

**Comment by mmpfister** [comment]
The problematic Pubmed article seems to be [this one](https://pubmed.ncbi.nlm.nih.gov/33690889/). Loading this page in the browser takes approx. 50 seconds. Its ID _33690889_ is returned from the search query of pymed and its details are requested in a subsequent pymed request. The EFetch API request for this ID results in an error. 

So, we should either catch this exception (which is hard because it does not seem to be distinguishable from a typical network error) or simply exclude this specific Pubmed ID from all queries in pymed.

**Comment by michip** [comment]
Is it possible to set a timeout on a pymed query and throw a specific timeout error? Are other network errors currently catched by the task?

**Comment by mmpfister** [comment]
> Is it possible to set a timeout on a pymed query and throw a specific timeout error? Are other network errors currently catched by the task?

The issue with Pubmed was only temporary. At the moment, the exception is not thrown, so we will investigate this when it occurs again.
